# Generated by Django 4.0.1 on 2024-02-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users', 'Can view users'), ('assign_group', 'Can assign group to users'), ('assign_permission', 'Can assign permission to users'), ('view_dashboard', 'Can view dashboard')], 'verbose_name_plural': 'Users'},
        ),
    ]
