# Generated by Django 4.0.1 on 2024-02-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users', 'Can view users'), ('assign_group', 'Can assign group to users'), ('assign_permission', 'Can assign permission to users'), ('view_dashboard', 'Can view dashboard'), ('view_dashboard_users', 'Can view dashboard current users on dashboard')], 'verbose_name_plural': 'Users'},
        ),
    ]
