# Generated by Django 4.0.1 on 2024-02-01 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_picture', models.ImageField(upload_to='aspirant_pictures')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('other_name', models.CharField(max_length=100)),
                ('ballot_number', models.PositiveIntegerField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Aspirants',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=100)),
                ('election_year', models.PositiveIntegerField(null=True)),
                ('election_date', models.DateField()),
                ('election_time', models.TimeField()),
                ('ending_date', models.DateField()),
                ('ending_time', models.TimeField()),
                ('allow_multiple_votes', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Elections',
                'permissions': [('can_assign_commnissioner_role', 'Can assign commissioner role')],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Halls',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Polling Stations',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
                ('position_description', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.election')),
            ],
            options={
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Programmes',
            },
        ),
        migrations.CreateModel(
            name='YearClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.programme')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.aspirant')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Votes',
                'permissions': [('can_view_result', 'Can View Result')],
            },
        ),
        migrations.CreateModel(
            name='ElectorateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.hall')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.pollingstation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.yearclass')),
            ],
            options={
                'verbose_name_plural': 'Electorate Profiles',
                'permissions': [('add_electorate', 'Can add electorate'), ('delete_electorate', 'Can delete electorate'), ('change_electorate', 'Can change electorate'), ('view_electorate', 'Can view electorate')],
            },
        ),
        migrations.CreateModel(
            name='ElectoralCommissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root_app.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Electoral Commissioner',
            },
        ),
        migrations.AddField(
            model_name='aspirant',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.election'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.position'),
        ),
        migrations.CreateModel(
            name='AllowedPollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.election')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.pollingstation')),
            ],
            options={
                'verbose_name_plural': 'Allowed Polling Stations',
            },
        ),
    ]
