# Generated by Django 4.0.1 on 2024-02-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0002_alter_electorateprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='number_of_asp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
