# Generated by Django 4.0.1 on 2024-02-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0003_position_number_of_asp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
