# Generated by Django 4.0.1 on 2024-02-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0004_alter_aspirant_time_stamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspirant',
            options={'permissions': [('can_view_aspirants', 'Can view aspirants')], 'verbose_name_plural': 'Aspirants'},
        ),
    ]
