# Generated by Django 4.0.1 on 2024-02-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0005_alter_aspirant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'permissions': [('can_assign_commnissioner_role', 'Can assign commissioner role'), ('view_results', 'Can view results'), ('view_election_results_list', 'Can view election results list')], 'verbose_name_plural': 'Elections'},
        ),
    ]
