# Generated by Django 4.0.1 on 2024-02-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0007_alter_election_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electoralcommissioner',
            options={'permissions': [('verify_electorate', 'Can verify electorate')], 'verbose_name_plural': 'Electoral Commissioner'},
        ),
    ]
