# Generated by Django 4.0.1 on 2024-02-13 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root_app', '0008_alter_electoralcommissioner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedElectorates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_app.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Verified Electorates',
                'permissions': [('view_verified_electorates', 'Can view verifed electorates'), ('unverify_electorates', 'Can unverify electorates')],
            },
        ),
    ]
