# Generated by Django 4.0.1 on 2024-02-14 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root_app', '0009_verifiedelectorates'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedelectorates',
            name='verified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='VerifiedVoters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
