# Generated by Django 4.0.1 on 2024-02-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0011_rename_verifiedelectorates_verifiedelectorate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifiedelectorate',
            options={'permissions': [('unverify_electorates', 'Can unverify electorates')], 'verbose_name_plural': 'Verified Electorates'},
        ),
    ]
