# Generated by Django 4.0.1 on 2024-02-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0013_alter_verifiedelectorate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-time_stamp'], 'permissions': [('can_assign_commnissioner_role', 'Can assign commissioner role'), ('view_results', 'Can view results'), ('view_election_results_list', 'Can view election results list'), ('view_general_report', 'Can view general report'), ('view_detailed_report', 'Can view detailed report')], 'verbose_name_plural': 'Elections'},
        ),
    ]
