# Generated by Django 4.0.1 on 2024-02-26 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0016_currentelection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspirant',
            options={'ordering': ['ballot_number'], 'permissions': [('can_view_aspirants', 'Can view aspirants')], 'verbose_name_plural': 'Aspirants'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'permissions': [('can_view_result', 'Can View Result'), ('print_results', 'Can Print Result')], 'verbose_name_plural': 'Votes'},
        ),
    ]
