# Generated by Django 4.0.1 on 2024-03-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0017_alter_aspirant_options_alter_vote_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abv_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': ['Institution Info'],
            },
        ),
    ]
