# Generated by Django 4.0.1 on 2024-03-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0018_institutioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioninfo',
            name='logo',
            field=models.ImageField(default=1, upload_to='company_logo'),
            preserve_default=False,
        ),
    ]
